// Generated by https://quicktype.io

export interface Profile {
  show_line_numbers_for_fence:                        boolean;
  image_uploader:                                     string;
  "export.epub":                                      ExportEpub;
  copy_markdown_by_default:                           boolean;
  "NSWindow Frame SUUpdateAlert":                     string;
  recentFolder:                                       string[];
  NSNavPanelExpandedSizeForOpenMode:                  string;
  backgroundColor:                                    string;
  send_usage_info:                                    boolean;
  hasThemeFolder:                                     boolean;
  "sentry.io.tags":                                   SentryIoTags;
  uuid:                                               string;
  prettyIndent:                                       boolean;
  no_line_wrapping:                                   boolean;
  NSDocumentSuppressTempVersionStoreWarning:          boolean;
  WebAutomaticDashSubstitutionEnabled:                boolean;
  "NSWindow Frame NSSpellCheckerSubstitutionsPanel2": string;
  darkTheme:                                          string;
  pinFolder:                                          string;
  quitAfterWindowClose:                               boolean;
  strict_mode:                                        boolean;
  useTreeStyle:                                       boolean;
  enable_inline_math:                                 boolean;
  can_collapse_outline_panel:                         boolean;
  sidebar_tab:                                        string;
  "NSWindow Frame NSNavPanelAutosaveName":            string;
  backgroundColor2:                                   number[];
  noMagnification:                                    boolean;
  image_save_location:                                string;
  schemeAwareness:                                    boolean;
  fileSearchWholeWord:                                boolean;
  auto_expand_block:                                  boolean;
  enable_diagram:                                     boolean;
  SUEnableAutomaticChecks:                            boolean;
  SULastCheckTime:                                    Date;
  use_seamless_window:                                boolean;
  apply_image_move_for_web:                           boolean;
  noWarnigForDeleteFile:                              boolean;
  isTypeWriterMode:                                   boolean;
  verInitTime:                                        Date;
  NSNavLastRootDirectory:                             string;
  WebKitDeveloperExtras:                              boolean;
  preLinebreakOnExport:                               boolean;
  fileSearchCaseSensitive:                            boolean;
  SUAutomaticallyUpdate:                              boolean;
  NSNavLastUserSetHideExtensionButtonState:           boolean;
  match_pari_markdown:                                boolean;
  noWarnigForFocusMode:                               boolean;
  use_relative_path_for_img:                          boolean;
  isFocusMode:                                        boolean;
  kCountlyStoredDeviceIDKey:                          string;
  ClosedWindowFrame:                                  string;
  allow_image_upload:                                 boolean;
  useDarkTheme:                                       boolean;
  NSNavPanelExpandedSizeForSaveMode:                  string;
  SUUpdateGroupIdentifier:                            number;
  custom_image_save_location:                         string;
  SUHasLaunchedBefore:                                boolean;
  SUUpdateRelaunchingMarker:                          boolean;
  "NSWindow Frame SUStatusFrame":                     string;
  noHintForOpenLink:                                  boolean;
  theme:                                              string;
  "sidebar-width":                                    number;
  autoUpdateToDev:                                    boolean;
  always_show_wordcount:                              boolean;
  zoomFactor:                                         number;
  currentThemeFolder:                                 string;
  wordCountDelimiter:                                 number;
  WebAutomaticQuoteSubstitutionEnabled:               boolean;
  initialize_ver:                                     string;
  restoreWhenLaunch:                                  string;
  WebContinuousSpellCheckingEnabled:                  boolean;
  savedLastOpen:                                      SavedLastOpen;
  "NSWindow Frame _ClosedWindowFrame":                string;
}

export interface ExportEpub {
  arg: string;
}

export interface SavedLastOpen {
  type: string;
  data: number[];
}

export interface SentryIoTags {
  intance:    string;
  lang:       string;
  appVersion: string;
  logger:     string;
}

export interface SentryIoUser {
  id: string;
}
